#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Celerie                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A simple calorie counter that respects your privacy

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Ryan Latture
your_link                                 : https://github.com/latture
your_city                                 : San Francisco
email_address                             : ryan.latture@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           : latture
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Custom nutrition goals
    description                           : Set daily goals for calories and macro nutrients
    fontawesome_icon_name                 : cogs

  - title                                 : Extensive food database
    description                           : Search for foods by text. Pro users can search by scanning a barcode.
    fontawesome_icon_name                 : database
    
  - title                                 : Create custom foods
    description                           : When you can't find what you're looking for in the database
    fontawesome_icon_name                 : utensils

  - title                                 : Create recipes
    description                           : Conveniently log your favorite recipes
    fontawesome_icon_name                 : cookie-bite

  - title                                 : Privacy focused
    description                           : No ads or tracking
    fontawesome_icon_name                 : lock

# Theme Settings
topbar_color                              : "#358C5B"
topbar_transparency                       : 1.0
topbar_title_color                        : "#ffffff"

cover_image                               : # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#58AF7A"
feature_icons_background_color            : "#ffffff"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown